#!/usr/bin/env python

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nomconfig.ui'
#
# Created: Thu Aug 26 20:24:00 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.musicBox = QtGui.QCheckBox(self.centralwidget)
        self.musicBox.setGeometry(QtCore.QRect(90, 90, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.musicBox.setFont(font)
        self.musicBox.setChecked(False)
        self.musicBox.setObjectName("musicBox")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 20, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.soundBox = QtGui.QCheckBox(self.centralwidget)
        self.soundBox.setGeometry(QtCore.QRect(90, 140, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.soundBox.setFont(font)
        self.soundBox.setChecked(True)
        self.soundBox.setObjectName("soundBox")
        self.multiBox = QtGui.QCheckBox(self.centralwidget)
        self.multiBox.setGeometry(QtCore.QRect(10, 10, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.multiBox.setFont(font)
        self.multiBox.setChecked(False)
        self.multiBox.setObjectName("multiBox")
        self.playerSpeed = QtGui.QSpinBox(self.centralwidget)
        self.playerSpeed.setGeometry(QtCore.QRect(230, 270, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.playerSpeed.setFont(font)
        self.playerSpeed.setMinimum(1)
        self.playerSpeed.setMaximum(20)
        self.playerSpeed.setProperty("value", 8)
        self.playerSpeed.setObjectName("playerSpeed")
        self.playerLives = QtGui.QSpinBox(self.centralwidget)
        self.playerLives.setGeometry(QtCore.QRect(480, 300, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.playerLives.setFont(font)
        self.playerLives.setMinimum(1)
        self.playerLives.setMaximum(2)
        self.playerLives.setProperty("value", 2)
        self.playerLives.setObjectName("playerLives")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 270, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 340, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.enemySpeed = QtGui.QSpinBox(self.centralwidget)
        self.enemySpeed.setGeometry(QtCore.QRect(230, 340, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.enemySpeed.setFont(font)
        self.enemySpeed.setMinimum(1)
        self.enemySpeed.setMaximum(20)
        self.enemySpeed.setProperty("value", 6)
        self.enemySpeed.setObjectName("enemySpeed")
        self.applyButton = QtGui.QPushButton(self.centralwidget)
        self.applyButton.setGeometry(QtCore.QRect(440, 160, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.applyButton.setFont(font)
        self.applyButton.setObjectName("applyButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.musicBox.setText(QtGui.QApplication.translate("MainWindow", "Music", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.soundBox.setText(QtGui.QApplication.translate("MainWindow", "Sound Effects", None, QtGui.QApplication.UnicodeUTF8))
        self.multiBox.setText(QtGui.QApplication.translate("MainWindow", "Multiplayer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Player Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Monster Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))

